/**
 * The vehicle classes as tuning presets.
 * Gearboxes: six speeds everywhere, spaced geometrically. First to fifth cover
 * the range the class can reach on its own, so fifth is its top-speed gear;
 * sixth is an overdrive that only pulls on boost. Each is the default tuning with the
 * numbers that make the class: mass, engine, drivetrain, geometry, suspension.
 * Visual profiles live in render/carProfiles.ts under the same ids.
 */
import { DEFAULT_TUNING, cloneTuning, type VehicleTuning } from './tuning';

export type CarId = 'muscle' | 'compact' | 'heavy' | 'sports' | 'police' | 'offroad' | 'moto';
/** The classes; one added after the first five has its shell appended after the last body (traffic/bodies.ts). */
export const CAR_IDS: CarId[] = ['muscle', 'compact', 'heavy', 'sports', 'police', 'offroad', 'moto'];

function preset(overrides: Partial<VehicleTuning>): VehicleTuning {
  return { ...cloneTuning(DEFAULT_TUNING), ...overrides };
}

export const CAR_PRESETS: Record<CarId, VehicleTuning> = {
  /** Long-bonnet rear-drive coupe: the starter car. */
  muscle: cloneTuning(DEFAULT_TUNING),

  /**
   * Small front-drive hatch, the city car (M8.8 slice 2): quicker than the muscle car to about 80 km/h, level with it
   * at 100, slower above (short gears, a strong middle, a boxy drag); the tightest turn and the quickest to change
   * direction. Safe: drifts only on the handbrake.
   */
  compact: preset({
    mass: 1050,
    chassisHalfExtents: { x: 0.85, y: 0.34, z: 1.9 },
    chassisOffsetY: 0.46,
    centerOfMassY: 0.0,
    inertiaScale: { x: 1, y: 0.85, z: 1 },
    wheelBase: 2.45,
    trackWidth: 1.5,
    wheelRadius: 0.3,
    wheelWidth: 0.2,
    suspensionRestLength: 0.28,
    suspensionStiffness: 42000,
    suspensionDampingCompression: 3600,
    suspensionDampingRebound: 4800,
    antiRollStiffness: 14000,
    maxSteerDegLow: 36,
    maxSteerDegHigh: 6,
    steerSpeedRef: 30,
    steerRate: 7,
    torqueMax: 212,
    redlineRpm: 6600,
    torqueCurve: [0.7, 0.93, 1.0, 0.92, 0.8],
    gearRatios: [4.1, 2.9, 2.08, 1.51, 1.1, 0.8],
    finalDrive: 4.6,
    driveFrontShare: 1,
    lsdLock: 0.2,
    brakeTorque: 4200,
    brakeFrontBias: 0.66,
    wheelInertia: 0.9,
    muFront: 2.1,
    muRear: 2.25,
    powerOversteer: 0,
    driftMaxAngleDeg: 30,
    driftThrottlePush: 3200,
    drag: 1.3,
    downforce: 1.2,
    boostTorqueMul: 1.35,
    boostThrust: 2000,
  }),

  /** Delivery van: heavy, tall, soft, slow to turn, bulldozes. */
  heavy: preset({
    mass: 2400,
    chassisHalfExtents: { x: 1.0, y: 0.5, z: 2.7 },
    chassisOffsetY: 0.75,
    centerOfMassY: 0.05,
    inertiaScale: { x: 1.15, y: 1.1, z: 1.15 },
    wheelBase: 3.4,
    trackWidth: 1.8,
    wheelRadius: 0.4,
    wheelWidth: 0.3,
    suspensionAttachY: 0.22,
    suspensionRestLength: 0.36,
    suspensionStiffness: 90000,
    suspensionDampingCompression: 7500,
    suspensionDampingRebound: 9500,
    antiRollStiffness: 60000,
    maxSteerDegLow: 32,
    maxSteerDegHigh: 4.5,
    steerSpeedRef: 28,
    steerRate: 4.5,
    torqueMax: 380,
    redlineRpm: 5200,
    gearRatios: [4.67, 3.27, 2.3, 1.61, 1.13, 0.93],
    finalDrive: 4.0,
    brakeTorque: 9500,
    handbrakeTorque: 6000,
    wheelInertia: 2.0,
    muFront: 2.0,
    muRear: 2.1,
    slipAngPeakDeg: 9,
    powerOversteer: 0.08,
    driftMaxAngleDeg: 28,
    driftAngleGain: 260000,
    driftYawTorqueMax: 60000,
    driftThrottlePush: 7000,
    driftVelocityFollow: 2.2,
    tireForceHeight: 0.9,
    drag: 2.2,
    downforce: 1.0,
    airPitchTorque: 9000,
    airRollTorque: 7000,
    airLevelTorque: 50000,
    airAngularDamping: 12000,
    boostTorqueMul: 1.3,
    boostThrust: 4000,
  }),

  /** Low coupe: the fastest body in the game and the interceptor's base. Stiff, real downforce. */
  sports: preset({
    mass: 1180,
    chassisHalfExtents: { x: 0.92, y: 0.28, z: 2.1 },
    chassisOffsetY: 0.38,
    centerOfMassY: -0.12,
    inertiaScale: { x: 0.95, y: 0.9, z: 0.95 },
    wheelBase: 2.7,
    trackWidth: 1.76,
    wheelRadius: 0.34,
    wheelWidth: 0.3,
    suspensionRestLength: 0.26,
    suspensionStiffness: 78000,
    suspensionDampingCompression: 6400,
    suspensionDampingRebound: 8200,
    antiRollStiffness: 38000,
    maxSteerDegLow: 33,
    maxSteerDegHigh: 4.2,
    steerSpeedRef: 36,
    steerRate: 7,
    torqueMax: 300,
    redlineRpm: 8200,
    gearRatios: [3.85, 2.88, 2.15, 1.61, 1.2, 0.91],
    finalDrive: 3.9,
    brakeTorque: 7200,
    brakeFrontBias: 0.64,
    wheelInertia: 1.0,
    muFront: 2.45,
    muRear: 2.5,
    slipAngPeakDeg: 7.5,
    powerOversteer: 0.18,
    driftMaxAngleDeg: 32,
    drag: 0.95,
    downforce: 3.0,
    boostTorqueMul: 1.3,
    boostThrust: 3200,
  }),

  /** Patrol saloon: a muscle car plus 300 kg, tuned to ram. Mass and yaw inertia carry the hit; a planted rear keeps a miss pointed at the player. */
  police: preset({
    mass: 1620,
    chassisHalfExtents: { x: 0.98, y: 0.34, z: 2.3 },
    chassisOffsetY: 0.44,
    centerOfMassY: -0.02,
    inertiaScale: { x: 1.05, y: 1.15, z: 1.05 },
    wheelBase: 3.0,
    trackWidth: 1.78,
    wheelRadius: 0.37,
    wheelWidth: 0.29,
    suspensionRestLength: 0.3,
    suspensionStiffness: 84000,
    suspensionDampingCompression: 6800,
    suspensionDampingRebound: 8600,
    antiRollStiffness: 40000,
    maxSteerDegLow: 33,
    maxSteerDegHigh: 5,
    steerSpeedRef: 36,
    torqueMax: 290,
    redlineRpm: 7000,
    gearRatios: [4.21, 3.11, 2.3, 1.7, 1.26, 0.98],
    finalDrive: 4.0,
    brakeTorque: 6800,
    brakeFrontBias: 0.63,
    wheelInertia: 1.3,
    muFront: 2.25,
    muRear: 2.3,
    powerOversteer: 0.05,
    driftMaxAngleDeg: 26,
    driftThrottlePush: 5600,
    drag: 1.18,
    downforce: 2.2,
    wallHitRetainSpin: 0.08,
    boostTorqueMul: 1.25,
    boostThrust: 2800,
  }),

  /**
   * The 4×4 (M8.8 slice 10): high on long soft springs and big wheels, four-wheel drive, a torquey engine that runs
   * out of revs early. Slower than the muscle car on the road; on grass and dirt its tyres keep nearly all their grip.
   */
  offroad: preset({
    mass: 1950,
    chassisHalfExtents: { x: 0.98, y: 0.46, z: 2.3 },
    chassisOffsetY: 0.72,
    centerOfMassY: 0.02,
    inertiaScale: { x: 1.1, y: 1.05, z: 1.1 },
    wheelBase: 2.8,
    trackWidth: 1.72,
    wheelRadius: 0.42,
    wheelWidth: 0.32,
    suspensionAttachY: 0.2,
    suspensionRestLength: 0.42,
    suspensionStiffness: 62000,
    suspensionDampingCompression: 5600,
    suspensionDampingRebound: 7400,
    antiRollStiffness: 42000,
    maxSteerDegLow: 34,
    maxSteerDegHigh: 5,
    steerSpeedRef: 30,
    steerRate: 5.5,
    torqueMax: 360,
    redlineRpm: 6000,
    torqueCurve: [0.75, 0.95, 1.0, 0.9, 0.75],
    gearRatios: [4.4, 3.05, 2.15, 1.56, 1.15, 0.92],
    finalDrive: 3.35,
    driveFrontShare: 0.45,
    brakeTorque: 8200,
    handbrakeTorque: 5000,
    wheelInertia: 1.8,
    muFront: 2.0,
    muRear: 2.05,
    grassGrip: 0.95,
    grassRoll: 1.5,
    dirtGrip: 1.0,
    dirtRoll: 1.2,
    sandGrip: 1.0,
    sandRoll: 1.2,
    slipAngPeakDeg: 9,
    powerOversteer: 0.06,
    driftMaxAngleDeg: 28,
    driftAngleGain: 220000,
    driftYawTorqueMax: 52000,
    driftThrottlePush: 6000,
    tireForceHeight: 0.9,
    drag: 1.45,
    downforce: 1.0,
    airPitchTorque: 7500,
    airRollTorque: 6000,
    airLevelTorque: 42000,
    airAngularDamping: 10000,
    boostTorqueMul: 1.3,
    boostThrust: 3600,
  }),

  /**
   * The motorbike (M8.8 slice 14): 290 kg with its rider on two wheels, the car model's four rays on a 0.1 m track
   * (`twoWheel`), the upright controller leaning it into the turn and letting go in a fall; a twin to 11,000 rpm.
   */
  moto: preset({
    mass: 290,
    chassisHalfExtents: { x: 0.35, y: 0.45, z: 1.05 },
    chassisOffsetY: 0.5,
    centerOfMassY: -0.1,
    inertiaScale: { x: 1, y: 1, z: 1 },
    wheelBase: 1.45,
    trackWidth: 0.1,
    wheelRadius: 0.32,
    wheelWidth: 0.16,
    suspensionAttachY: 0.1,
    suspensionRestLength: 0.25,
    suspensionStiffness: 26000,
    suspensionDampingCompression: 2600,
    suspensionDampingRebound: 3400,
    bumpStopStiffness: 60000,
    suspensionDampingProgressive: 100,
    antiRollStiffness: 0,
    maxSteerDegLow: 32,
    maxSteerDegHigh: 4,
    steerSpeedRef: 30,
    steerRate: 6,
    torqueMax: 95,
    idleRpm: 1400,
    redlineRpm: 11000,
    engineBrakeTorque: 12,
    engineInertia: 0.1,
    gearRatios: [2.6, 1.9, 1.5, 1.25, 1.08, 0.95],
    finalDrive: 3.6,
    driveFrontShare: 0,
    lsdPreload: 10,
    lsdStiffness: 50,
    brakeTorque: 1500,
    brakeFrontBias: 0.65,
    handbrakeTorque: 900,
    wheelInertia: 0.25,
    tireForceHeight: 0.4,
    driftAngleGain: 30000,
    driftAngleDamping: 2000,
    driftYawTorqueMax: 7000,
    driftThrottlePush: 1200,
    drag: 0.52,
    downforce: 0.3,
    airPitchTorque: 800,
    airRollTorque: 700,
    airLevelTorque: 8000,
    airAngularDamping: 1100,
    // a short wheelbase follows its flight steeply: held to 12° it lands on both wheels
    airPitchMaxDeg: 12,
    twoWheel: 1,
    // stiff enough to hold the lean of the turn's g within a degree or two against the fall
    leanGain: 220,
    leanDamping: 30,
    boostTorqueMul: 1.25,
    boostThrust: 600,
  }),
};
