/**
 * The game in Polish (docs/DESIGN.md §19, Marcin 2026-09-24: the default language). The key is the English text the
 * code writes; the value is what a Polish player reads. `{name}` is a hole the caller fills (a value keeps its key's
 * holes: pinned); `{n|one|few|many}` is a Polish count's form, picked by the number in `n` (1 ELIMINACJA,
 * 2 ELIMINACJE, 5 ELIMINACJI). A key the table lacks is said as written (a pin says none is missing).
 *
 * One name for each thing (§17.4 in Polish): BANK; ŁUP for the bag; the stars (GWIAZDKI); GARAŻ; GLINY for the
 * police (RADIOWÓZ for the car); KOMBO; PREMIA DO ŁUPU; and ELIMINACJA for a takedown, WPADKA for busted, NITRO for
 * the boost, WYPAD for a run, ZLECENIE for a job. The names are Polish too (a Polish child reads PALMOWE OGRODY),
 * the rivals keep their alliteration. A paint agrees with its car: `PL_GENDER` and `PL_PAINT`. A car or a rival
 * stands in a sentence after a colon, in the form its name has (KUP: KOMPAKT), so no name needs another case.
 */
export const PL: Readonly<Record<string, string>> = {
  // the driving screen (hud.ts, corners.ts) and the keys
  'km/h': 'km/h',
  'BOOST': 'NITRO',
  'DAMAGE': 'USZKODZENIA',
  'WRECKED': 'WRAK',
  'SWAP': 'PRZESIĄDŹ SIĘ',
  'BORROW': 'POŻYCZ',
  "COPS WON'T KNOW YOU · {s} s": 'GLINY CIĘ NIE POZNAJĄ · {s} s',
  '{swap} take a car  ·  {reset} respawn': '{swap} weź auto  ·  {reset} od nowa',
  'SOUND ON': 'DŹWIĘK WŁĄCZONY',
  'MUTED': 'WYCISZONO',
  'PAUSED': 'PAUZA',
  'press {key} to continue': 'naciśnij {key}, aby grać dalej',
  'click the game to continue': 'kliknij grę, aby grać dalej',
  'LAST': 'OSTATNIE',
  'BEST': 'REKORD',
  'BEST LAP {time}': 'REKORD OKRĄŻENIA {time}',
  'LAP {time}': 'OKRĄŻENIE {time}',
  'drive': 'jazda',
  'drift (or brake + turn)': 'drift (albo hamulec + skręt)',
  'boost': 'nitro',
  'reset': 'reset',
  'camera': 'kamera',
  'map (hold)': 'mapa (przytrzymaj)',
  'horn': 'klakson',
  'pause': 'pauza',
  'tuning': 'tuning',
  'SPACE': 'SPACJA',
  'SHIFT': 'SHIFT',
  'ENTER': 'ENTER',
  'TAB': 'TAB',

  // the pause screen's settings (settings.ts)
  'MUSIC': 'MUZYKA',
  'EFFECTS': 'EFEKTY',
  'QUALITY': 'GRAFIKA',
  'RADAR': 'RADAR',
  'LANGUAGE': 'JĘZYK',
  'AUTO': 'AUTO',
  'LOW': 'NISKA',
  'HIGH': 'WYSOKA',
  'NORTH UP': 'PÓŁNOC U GÓRY',
  'TURNS': 'OBRACA SIĘ',

  // one voice at a time (voice.ts): the top centre and the pops
  'COPS ON YOUR TAIL': 'GLINY NA OGONIE',
  'FAST COP CARS ON THE ROAD': 'SZYBKIE RADIOWOZY NA DRODZE',
  'ROADBLOCKS UP': 'BLOKADY NA DROGACH',
  'HEAVY SUVS ROLLING': 'CIĘŻKIE SUV-Y RUSZAJĄ',
  'THE CHIEF IS COMING': 'NADCIĄGA KOMENDANT',
  'DISPATCH': 'CENTRALA',
  'ROADBLOCK AHEAD': 'BLOKADA PRZED TOBĄ',
  'HELICOPTER ON YOU': 'HELIKOPTER NAD TOBĄ',
  'SUSPECT IN A {car}': 'PODEJRZANY: {car}',
  'BOARD': 'LISTA',
  'RADIO': 'RADIO',
  'THE TWINS SWAPPED · NOW IN A {car}': 'BLIŹNIĘTA ZMIENIŁY AUTO · TERAZ: {car}',
  'TAKEDOWN!': 'ELIMINACJA!',
  'TAKEDOWN! INTO TRAFFIC!': 'ELIMINACJA! PROSTO W RUCH!',
  'BILLBOARD {n}/{of}': 'BILLBOARD {n}/{of}',
  'BILLBOARD!': 'BILLBOARD!',
  'COPS LOST YOU': 'GLINY CIĘ ZGUBIŁY',
  'FLASHED {kmh} KM/H': 'FOTORADAR: {kmh} KM/H',
  'STUNT! {s} S': 'SKOK! {s} S',
  'DAILY DONE +{cash}': 'WYZWANIE DNIA +{cash}',
  'DAY {day} STREAK +{cash}': 'SERIA: DZIEŃ {day} +{cash}',
  'COVER BLOWN': 'PRZYKRYWKA SPALONA',
  'CACHE {n}/{of} +{cash}': 'SKRYTKA {n}/{of} +{cash}',
  'CACHE {n}/{of}': 'SKRYTKA {n}/{of}',
  'CHASE +{cash}': 'POŚCIG +{cash}',
  'COMBO +{cash}': 'KOMBO +{cash}',
  'COMBO LOST': 'KOMBO STRACONE',
  'ALL {n} JUMPS +{cash}': 'WSZYSTKIE {n} {n|SKOK|SKOKI|SKOKÓW} +{cash}',
  'NEW JUMP {n}/{of}': 'NOWY SKOK {n}/{of}',
  'ALL BILLBOARDS +{cash}': 'WSZYSTKIE BILLBOARDY +{cash}',
  'HIDDEN CAR FOUND · IN THE GARAGE NOW': 'UKRYTE AUTO ZNALEZIONE · JUŻ W GARAŻU',
  'PURSUIT BREAKER!': 'PUŁAPKA!',

  // the goal line and the job's card (jobs.ts)
  'DELIVERY': 'DOSTAWA',
  'STEAL TO ORDER': 'KRADZIEŻ NA ZAMÓWIENIE',
  'ESCAPE': 'UCIECZKA',
  'TIME TRIAL': 'JAZDA NA CZAS',
  'STREET RACE': 'WYŚCIG ULICZNY',
  'TAKEDOWN RAGE': 'SZAŁ ELIMINACJI',
  'MAYHEM': 'ROZRÓBA',
  'FARE': 'KURS',
  'WANTED BOARD': 'LISTA POSZUKIWANYCH',
  'TAKE A JOB': 'WEŹ ZLECENIE',
  'BANK IT': 'WPŁAĆ ŁUP',
  'LOSE THEM OR BANK IT': 'ZGUB ICH ALBO WPŁAĆ ŁUP',
  'LOSE THEM': 'ZGUB ICH',
  'BUY THE {car}': 'KUP: {car}',
  '{cash} TO GO': 'BRAKUJE {cash}',
  'ESCAPE THE COPS': 'UCIEKNIJ GLINOM',
  'FILL THE BAG': 'POWIĘKSZ ŁUP',
  'FACE THE CHIEF': 'ZMIERZ SIĘ Z KOMENDANTEM',
  'CHALLENGE {name}': 'WYZWIJ: {name}',
  '#{n} NEEDS: {req}': '#{n} WYMAGA: {req}',
  'REMATCH WON +{cash}': 'REWANŻ WYGRANY +{cash}',
  'BEATEN +{cash} · THE {car} IS YOURS': 'WYGRANA +{cash} · {car} JUŻ W GARAŻU',
  'TOO LATE · TRY AGAIN': 'ZA PÓŹNO · SPRÓBUJ JESZCZE RAZ',
  '{name} GOT HOME · TRY AGAIN': '{name} U CELU · SPRÓBUJ JESZCZE RAZ',
  '{name} WINS · TRY AGAIN': '{name} WYGRYWA · SPRÓBUJ JESZCZE RAZ',
  '{name} WIN · TRY AGAIN': '{name} WYGRYWAJĄ · SPRÓBUJ JESZCZE RAZ',
  'LOSE THE CHIEF': 'ZGUB KOMENDANTA',
  'WRECK {name}': 'ROZBIJ: {name}',
  'SOLD': 'SPRZEDANE',
  'BOUNTY': 'NAGRODA',
  '{place} PLACE': '{place}',
  'RAGE DONE': 'SZAŁ ZALICZONY',
  'MAYHEM DONE': 'ROZRÓBA ZALICZONA',
  'FARE PAID': 'KURS OPŁACONY',
  'DELIVERED': 'DOSTARCZONO',
  'CLEAN LINE': 'CZYSTA JAZDA',
  'TOO SLOW · NO MEDAL': 'ZA WOLNO · BEZ MEDALU',
  'LAST · NO PRIZE': 'OSTATNIE MIEJSCE · BEZ NAGRODY',
  'TOO LATE': 'ZA PÓŹNO',
  'FIND A {car}': 'ZNAJDŹ: {car}',
  'DELIVER THE {car}': 'DOSTARCZ: {car}',
  'ESCAPE {stars}': 'UCIECZKA {stars}',
  'TIME TRIAL · FOLLOW THE COINS': 'JAZDA NA CZAS · JEDŹ ZA MONETAMI',
  'RACE · {place}': 'WYŚCIG · {place}',
  'HOT FARE': 'GORĄCY KURS',
  'TIPS +{cash}': 'NAPIWKI +{cash}',
  '{n}/{of} TAKEDOWNS': 'ELIMINACJE: {n}/{of}',
  'RAGE': 'SZAŁ',
  'BACK INTO THE ZONE': 'WRÓĆ DO STREFY',
  'LOSE HIM AT ★★★★★': 'ZGUB GO PRZY ★★★★★',
  'WRECK THE {car} BEFORE IT GETS HOME': 'ROZBIJ: {car} · ZANIM DOJEDZIE',
  'FIRST TO THE FINISH · ANY ROUTE': 'KTO PIERWSZY NA METĘ · DOWOLNA TRASA',
  'REMATCH · {cash}': 'REWANŻ · {cash}',
  '{cash} + THE {car}': '{cash} + {car}',
  "WANTED: {car} · IT'S IN TRAFFIC · SWAP INTO IT": 'ZAMÓWIENIE: {car} · JEŹDZI W RUCHU · PRZESIĄDŹ SIĘ',
  'WANTED: {car}': 'ZAMÓWIENIE: {car}',
  '{time} FROM THE SWAP · NO SCRATCHES': '{time} OD PRZESIADKI · BEZ RYSY',
  'THE COPS HAVE YOU': 'GLINY CIĘ MAJĄ',
  'A CROOK WITH A SUITCASE · DOUBLE PAY · MORE STARS': 'KANCIARZ Z WALIZKĄ · PODWÓJNA STAWKA · WIĘCEJ GWIAZDEK',
  'TAKE THEM THERE · FOLLOW THE LINE': 'ZAWIEŹ PASAŻERA · JEDŹ ZA LINIĄ',
  '{time} · NEAR MISSES AND JUMPS TIP': '{time} · NAPIWKI ZA SKOKI I MIJANKI O WŁOS',
  'WRECK CARS INSIDE THE RING': 'ROZBIJAJ AUTA W KRĘGU',
  'SMASH IT UP INSIDE THE RING': 'DEMOLUJ WSZYSTKO W KRĘGU',
  '{n} TAKEDOWNS IN {s} S': '{n} {n|ELIMINACJA|ELIMINACJE|ELIMINACJI} W {s} S',
  '{cash} OF DAMAGE IN {s} S': '{cash} SZKÓD W {s} S',
  '1ST {a} · 2ND {b} · 3RD {c}': '1. {a} · 2. {b} · 3. {c}',
  'FOLLOW THE COINS · YOUR BEST: {medal}': 'JEDŹ ZA MONETAMI · TWÓJ REKORD: {medal}',
  'FOLLOW THE COINS TO THE FINISH': 'JEDŹ ZA MONETAMI DO METY',
  'GOLD {g} · SILVER {s} · BRONZE {b}': 'ZŁOTO {g} · SREBRO {s} · BRĄZ {b}',
  'DELIVER IT · FOLLOW THE LINE': 'DOSTARCZ PACZKĘ · JEDŹ ZA LINIĄ',
  '{time} · FASTER PAYS MORE': '{time} · IM SZYBCIEJ, TYM WIĘCEJ',
  'STEP {n} OF {of}': 'KROK {n} Z {of}',
  'DONE': 'ZROBIONE',
  'ALL DONE · THE CITY IS YOURS': 'WSZYSTKO ZROBIONE · MIASTO JEST TWOJE',
  'NEXT: {step}': 'DALEJ: {step}',

  // the full map (bigmap.ts) and the radar (minimap.ts)
  'RIVAL': 'RYWAL',
  'BILLBOARDS {n}/{of}': 'BILLBOARDY {n}/{of}',
  'JUMPS {n}/{of}': 'SKOKI {n}/{of}',
  'CACHES {n}/{of}': 'SKRYTKI {n}/{of}',
  'MAP': 'MAPA',
  'HOLD {key}': 'PRZYTRZYMAJ {key}',
  'YOU': 'TY',
  'GARAGE': 'GARAŻ',
  'CACHE': 'SKRYTKA',
  'SPEED CAMERA': 'FOTORADAR',
  'PURSUIT BREAKER': 'PUŁAPKA NA POŚCIG',
  'COVER': 'OSŁONA',
  'COPS': 'GLINY',
  'HELICOPTER': 'HELIKOPTER',
  'Map of the island, north up. The yellow arrow is your car.': 'Mapa wyspy, północ u góry. Żółta strzałka to twoje auto.',
  'Radar map. Up is your direction of travel. The yellow arrow is your car; the cyan line is the way to your goal.': 'Radar. U góry jest kierunek jazdy. Żółta strzałka to twoje auto, turkusowa linia to droga do celu.',

  // the run: the busted card and the wall's TOTALS (run.ts, totals.ts)
  'BUSTED': 'WPADKA',
  'CRIMES FILL THE BAG · STARS MULTIPLY IT · A GARAGE BANKS IT': 'PRZESTĘPSTWA DAJĄ ŁUP · GWIAZDKI GO MNOŻĄ · GARAŻ GO WPŁACA',
  'BANKED': 'W BANKU',
  'NEW BEST': 'NOWY REKORD',
  'ANY KEY': 'DOWOLNY KLAWISZ',
  'Bag': 'Łup',
  'BAG {cash}': 'ŁUP {cash}',
  'DOUBLED': 'PODWOJONY',
  'BAG BONUS': 'PREMIA DO ŁUPU',
  'THE LAWYER KEEPS 3/4': 'PRAWNIK RATUJE 3/4',
  'YOU KEEP HALF': 'ZOSTAJE CI POŁOWA',
  'BANK': 'BANK',
  'FIRST NEW CAR: {price} · IT IS YOURS IN CARS': 'PIERWSZE NOWE AUTO: {price} · STAĆ CIĘ · ZAKŁADKA AUTA',
  'FIRST NEW CAR: {price} · YOU HAVE {bank}': 'PIERWSZE NOWE AUTO: {price} · MASZ {bank}',
  'NEXT: {step} · STEP {n} OF {of}': 'DALEJ: {step} · KROK {n} Z {of}',
  '{n} {n|TAKEDOWN|TAKEDOWNS}': '{n} {n|ELIMINACJA|ELIMINACJE|ELIMINACJI}',
  '{n} {n|ESCAPE|ESCAPES}': '{n} {n|UCIECZKA|UCIECZKI|UCIECZEK}',
  '{n} {n|BILLBOARD|BILLBOARDS}': '{n} {n|BILLBOARD|BILLBOARDY|BILLBOARDÓW}',
  '{n} {n|COIN|COINS}': '{n} {n|MONETA|MONETY|MONET}',
  'CITY DAMAGE {cash}': 'SZKODY W MIEŚCIE {cash}',
  'NEXT ON THE BOARD: {who} · READY FOR YOU': 'DALEJ NA LIŚCIE: {who} · CZEKA NA CIEBIE',
  'NEXT ON THE BOARD: {who} · {req}': 'DALEJ NA LIŚCIE: {who} · {req}',

  // the wall behind the door (garage.ts, wallPages.ts)
  'TOTALS': 'WYNIK',
  'CARS': 'AUTA',
  'STYLE': 'STYL',
  'GOALS': 'CELE',
  'WHEELS · THIS CAR': 'KOŁA · TYLKO TO AUTO',
  'SPOILER · THIS CAR': 'SPOJLER · TYLKO TO AUTO',
  'STANCE · THIS CAR': 'ZAWIESZENIE · TYLKO TO AUTO',
  'ON THE ROOF · YOURS, IN EVERY CAR YOU TAKE': 'NA DACHU · ZAWSZE Z TOBĄ, W KAŻDYM AUCIE',
  'NEON · YOURS': 'NEON · ZAWSZE Z TOBĄ',
  'HORN · H · YOURS': 'KLAKSON · H · ZAWSZE Z TOBĄ',
  'BOOST FLAME · YOURS': 'PŁOMIEŃ NITRO · ZAWSZE Z TOBĄ',
  'TYRE SMOKE · YOURS': 'DYM Z OPON · ZAWSZE Z TOBĄ',
  'POWER': 'MOC',
  'GRIP': 'PRZYCZEPNOŚĆ',
  'LAWYER': 'PRAWNIK',
  'BUSTED: KEEP 3/4 OF THE BAG': 'WPADKA: ZOSTAJE CI 3/4 ŁUPU',
  'THE GARAGE PAYS +0.5 × ON THE BAG': 'GARAŻ DOLICZA +0,5 × DO ŁUPU',
  'DOUBLE THE BAG': 'PODWÓJ ŁUP',
  'FREE': 'ZA DARMO',
  'FOR THE NEXT RUN': 'NA NASTĘPNY WYPAD',
  'TODAY': 'DZIŚ',
  'DRIVE OUT': 'WYJEDŹ',
  'watch a video': 'obejrzyj film',
  'paint {hex}': 'lakier {hex}',
  'CARS {n}/{of} · DRIVE ANY CAR HOME TO KEEP IT': 'AUTA {n}/{of} · WJEDŹ AUTEM DO GARAŻU, A BĘDZIE TWOJE',
  'SELECTED': 'WYBRANE',
  'OWNED': 'TWOJE',
  'ESCAPE ★★★★★ FIRST': 'NAJPIERW UCIEKNIJ PRZY ★★★★★',
  'KEEP IT {cash}': 'ZATRZYMAJ {cash}',
  'PAINT: {car} · FREE': 'LAKIER: {car} · ZA DARMO',
  'NOT ON THIS CAR': 'NIE DO TEGO AUTA',
  'FITTED': 'ZAMONTOWANE',
  'WORN': 'ZAŁOŻONE',
  'FIT IT': 'ZAMONTUJ',
  'WEAR IT': 'ZAŁÓŻ',
  '7-DAY STREAK': 'SERIA 7 DNI',
  'BEAT {name}': 'POKONAJ: {name}',
  'TODAY {cash}': 'DZIŚ {cash}',
  'UPGRADES: {car}': 'ULEPSZENIA: {car}',
  'MAX': 'MAKS',
  'BOUGHT': 'KUPIONE',
  'THE WANTED BOARD · YOU ARE #1': 'LISTA POSZUKIWANYCH · JESTEŚ #1',
  'THE WANTED BOARD · NOT ON IT YET': 'LISTA POSZUKIWANYCH · JESZCZE CIĘ NA NIEJ NIE MA',
  'THE WANTED BOARD · YOU ARE #{n}': 'LISTA POSZUKIWANYCH · JESTEŚ #{n}',
  'EVERY RIVAL BEATEN · A REMATCH PAYS A QUARTER': 'WSZYSCY RYWALE POKONANI · REWANŻ PŁACI ĆWIERĆ',
  'THE HIGHWAY': 'OBWODNICA',
  'NEXT: #{n} {name}': 'DALEJ: #{n} {name}',
  'LAST: {name}': 'NA KONIEC: {name}',
  'BEST {cash}': 'REKORD {cash}',
  'READY · THE CYAN RING IS ON THE MAP': 'GOTOWE · BŁĘKITNY KRĄG JEST NA MAPIE',
  'HUNTS: {list}': 'ZNAJDŹKI: {list}',
  '{n} {medal}': '{medal} ×{n}',
  'TIME TRIAL MEDALS: {list}': 'MEDALE ZA JAZDĘ NA CZAS: {list}',
  'BEST RUN {cash}': 'NAJLEPSZY WYPAD {cash}',
  'TODAY · STREAK DAY {n}': 'DZIŚ · SERIA: DZIEŃ {n}',
  'TOPPER ON': 'OZDOBA NA DACHU',
  '{l} {r} CHOOSE · {c} OK': '{l} {r} WYBIERZ · {c} OK',
  '{l} {r} PICK · {c} {b} ROWS · {s} OK': '{l} {r} WYBÓR · {c} {b} RZĘDY · {s} OK',
  '{l} {r} PICK · {c} OK · {b} BACK': '{l} {r} WYBÓR · {c} OK · {b} WRÓĆ',
  '{r} CARS · {c} DRIVE OUT': '{r} AUTA · {c} WYJEDŹ',
  '{l} {r} PAGES · {c} OPEN · {b} TOTALS': '{l} {r} STRONY · {c} OTWÓRZ · {b} WYNIK',

  // the cold open's captions (coldOpen.ts)
  'DRIVE': 'JEDŹ',
  'SMASH THE BILLBOARD': 'ROZWAL BILLBOARD',
  'RAM THEM INTO A WALL': 'WBIJ ICH W ŚCIANĘ',
  'PICK UP THE PACKAGE · SLOW DOWN IN THE RING': 'ODBIERZ PACZKĘ · ZWOLNIJ W KÓŁKU',
  'SLOW DOWN IN THE RING': 'ZWOLNIJ W KÓŁKU',
  'JOB': 'ZLECENIE',
  'NEW: {kind}': 'NOWOŚĆ: {kind}',
  'LOOK FOR ITS SIGN': 'SZUKAJ JEGO ZNAKU',
  'A WANTED CAR · SWAP INTO IT': 'ZAMÓWIONE AUTO · PRZESIĄDŹ SIĘ',
  'GET IT TO THE GARAGE': 'ZAWIEŹ JĄ DO GARAŻU',
  'SKIP': 'POMIŃ',

  // the boot (app/bootWatch.ts, main.ts) and the app's own toasts
  'PLATFORM': 'PLATFORMA',
  'PHYSICS': 'FIZYKA',
  'SAVE': 'ZAPIS',
  'CITY': 'MIASTO',
  'GRAPHICS': 'GRAFIKA',
  'FIRST FRAME': 'PIERWSZA KLATKA',
  'STILL LOADING · CLICK TO RETRY': 'WCIĄŻ WCZYTUJĘ · KLIKNIJ, BY SPRÓBOWAĆ ZNOWU',
  'LOADING · {phase}': 'WCZYTYWANIE · {phase}',
  'LOADING': 'WCZYTYWANIE',
  'FAILED TO START': 'NIE UDAŁO SIĘ URUCHOMIĆ GRY',
  'GHOST LOADED': 'DUCH WCZYTANY',
  'BAD RECORDING': 'ZŁE NAGRANIE',

  // the wanted board's requirements (sim/board/rivals.ts `reqText`)
  'FINISH THE FIRST SIX STEPS': 'UKOŃCZ PIERWSZE SZEŚĆ KROKÓW',
  'WIN A STREET RACE': 'WYGRAJ WYŚCIG ULICZNY',
  'WIN {n} STREET RACES': 'WYGRAJ {n} {n|WYŚCIG ULICZNY|WYŚCIGI ULICZNE|WYŚCIGÓW ULICZNYCH}',
  '{medal} ON A TIME TRIAL': '{medal} W JEŹDZIE NA CZAS',
  '{medal} ON {n} TIME TRIALS': '{medal} W {n} JAZDACH NA CZAS',
  'ESCAPE AT {stars}': 'UCIEKNIJ PRZY {stars}',
  '{n} TAKEDOWNS': '{n} {n|ELIMINACJA|ELIMINACJE|ELIMINACJI}',
  'WIN A RAGE OR MAYHEM ZONE': 'WYGRAJ SZAŁ LUB ROZRÓBĘ',
  'WIN {n} RAGE OR MAYHEM ZONES': 'WYGRAJ {n} {n|STREFĘ|STREFY|STREF} SZAŁU LUB ROZRÓBY',
  'DELIVER {n} TAXI FARES': 'ZALICZ {n} {n|KURS|KURSY|KURSÓW} TAKSÓWKĄ',
  'DELIVER {n} CARS TO ORDER': 'DOSTARCZ {n} {n|AUTO|AUTA|AUT} NA ZAMÓWIENIE',
  'OWN {n} CARS': 'ZDOBĄDŹ {n} {n|AUTO|AUTA|AUT}',
  '{n} STUNT JUMPS': '{n} {n|SKOK|SKOKI|SKOKÓW}',
  'BANK {n} IN ONE RUN': 'WPŁAĆ {n} W JEDNYM WYPADZIE',
  '{n} BILLBOARDS': '{n} {n|BILLBOARD|BILLBOARDY|BILLBOARDÓW}',
  'A HOT FARE': 'GORĄCY KURS',
  '{n} HOT FARES': '{n} {n|GORĄCY KURS|GORĄCE KURSY|GORĄCYCH KURSÓW}',
  '{n} CACHES': '{n} {n|SKRYTKA|SKRYTKI|SKRYTEK}',
  'BEAT THE TEN': 'POKONAJ DZIESIĄTKĘ',
  'SMASH {n} THINGS': 'ROZWAL {n} {n|RZECZ|RZECZY|RZECZY}',

  // the rivals: a name, the poster's line, what the radio says (sim/board/rivals.ts)
  'GRANNY GEARS': 'BABCIA BRYKA',
  'SPEEDING SINCE 1962': 'GAZ DO DECHY OD 1962',
  'WANTS A RACE': 'CHCE SIĘ ŚCIGAĆ',
  'PEPPERONI PETE': 'PEPPERONI PIOTREK',
  'THIRTY MINUTES OR IT IS FREE': 'TRZYDZIEŚCI MINUT ALBO GRATIS',
  'TOW TRUCK TINA': 'LAWETOWA LUCYNA',
  'EVERY CAR IN THE WORKS IS HERS SOONER OR LATER': 'KAŻDE AUTO W HUCIE PRĘDZEJ CZY PÓŹNIEJ BĘDZIE JEJ',
  'IS OUT WITH A BAG': 'JEDZIE Z ŁUPEM',
  'THE TWINS': 'BLIŹNIĘTA',
  'THEY NEVER DRIVE THE SAME CAR TWICE': 'NIGDY NIE JADĄ DWA RAZY TYM SAMYM AUTEM',
  'WANT A RACE': 'CHCĄ SIĘ ŚCIGAĆ',
  'FAKE FRANK': 'FAŁSZYWY FRANEK',
  'NOT A POLICEMAN. NEVER WAS': 'ŻADEN POLICJANT. NIGDY NIM NIE BYŁ',
  'BIG BERNIE': 'WIELKI WIESIEK',
  'NEXT STOP: THE FINISH LINE': 'NASTĘPNY PRZYSTANEK: META',
  'NEON NIKO': 'NEONOWY NIKO',
  'LOW, SLOW, THEN SUDDENLY NOT': 'NISKO, WOLNO, A NAGLE JUŻ NIE',
  "THE MAYOR'S NEPHEW": 'SIOSTRZENIEC BURMISTRZA',
  'HIS UNCLE PAYS THE POLICE': 'WUJEK OPŁACA POLICJĘ',
  'PROFESSOR PIP': 'PROFESOR PSTRYK',
  'BUILT IT IN A SHED': 'ZBUDOWAŁ GO W SZOPIE',
  'THE GHOST': 'DUCH',
  'NOBODY HAS SEEN THE FACE': 'NIKT NIE WIDZIAŁ TWARZY',
  'THE CHIEF': 'KOMENDANT',
  'HE WANTS HIS BOARD BACK': 'CHCE ODZYSKAĆ SWOJĄ LISTĘ',
  'WANTS HIS BOARD BACK': 'CHCE ODZYSKAĆ LISTĘ',

  // the medals and the places (sim/jobs/catalog.ts)
  'BRONZE': 'BRĄZ',
  'SILVER': 'SREBRO',
  'GOLD': 'ZŁOTO',
  '1ST': '1. MIEJSCE',
  '2ND': '2. MIEJSCE',
  '3RD': '3. MIEJSCE',
  '4TH': '4. MIEJSCE',

  // the cars (sim/jobs/catalog.ts); each one's gender is `PL_GENDER`'s
  'MUSCLE CAR': 'MUSCLE CAR',
  'COMPACT': 'KOMPAKT',
  'VAN': 'VAN',
  'SPORTS CAR': 'AUTO SPORTOWE',
  'POLICE CAR': 'RADIOWÓZ',
  'SEDAN': 'SEDAN',
  'HATCHBACK': 'HATCHBACK',
  'ESTATE': 'KOMBI',
  'SUV': 'SUV',
  'PICKUP': 'PICKUP',
  'TAXI': 'TAKSÓWKA',
  'BOX TRUCK': 'FURGON',
  'BUS': 'AUTOBUS',
  'ICE-CREAM TRUCK': 'WÓZ Z LODAMI',
  'WAGON': 'KOMBIAK',
  'PIZZA HATCH': 'PIZZOWÓZ',
  'WRECKER': 'LAWETA',
  'TWIN': 'BLIŹNIAK',
  'FAKE CRUISER': 'FAŁSZYWY RADIOWÓZ',
  'PARTY BUS': 'IMPREZOBUS',
  'LOWRIDER': 'LOWRIDER',
  'GOLD LIMO': 'ZŁOTA LIMUZYNA',
  'BUBBLE': 'BĄBEL',
  'PHANTOM': 'FANTOM',
  "CHIEF'S CRUISER": 'RADIOWÓZ KOMENDANTA',
  'ROADSTER': 'ROADSTER',
  'STREET SWEEPER': 'ZAMIATARKA',
  'HOT-DOG VAN': 'WÓZ Z HOT-DOGAMI',
  // what a car is for, under its name on the wall (M8.8 slice 3); DRIFT and CITY say what they say elsewhere
  'RAM': 'TARAN',
  'SPEED': 'PRĘDKOŚĆ',
  'DISGUISE': 'PRZEBRANIE',

  // the districts and their landmarks (sim/city/City.ts)
  'CROWN HEIGHTS': 'KORONNE WZGÓRZA',
  'SUNSET WORKS': 'HUTA ZACHÓD',
  'PALM GARDENS': 'PALMOWE OGRODY',
  'CORAL QUAY': 'KORALOWE NABRZEŻE',
  'Crown Tower': 'Wieża Koronna',
  'The Waterworks': 'Wodociągi',
  'Glasshouse': 'Palmiarnia',
  'Coral Hotel': 'Hotel Koral',

  // the combo's tricks (sim/run/Skill.ts) and the street furniture a smash names (sim/city/props.ts)
  'NEAR MISS': 'O WŁOS',
  'ONCOMING MISS': 'O WŁOS POD PRĄD',
  'ONCOMING': 'POD PRĄD',
  'DRIFT': 'DRIFT',
  'AIR': 'LOT',
  'SMASH': 'DEMOLKA',
  'LAMP POST': 'LATARNIA',
  'TREE': 'DRZEWKO',
  'HYDRANT': 'HYDRANT',
  'BIN': 'KOSZ',
  'PARKING METER': 'PARKOMAT',
  'BENCH': 'ŁAWKA',
  'NEWSPAPER BOX': 'SKRZYNKA NA GAZETY',
  'CAFÉ TABLE': 'STOLIK',
  'CHAIR': 'KRZESŁO',
  'BUS SHELTER': 'PRZYSTANEK',
  'NEWSSTAND': 'KIOSK',
  'PALLET': 'PALETA',
  'BARREL': 'BECZKA',
  'CRATE': 'SKRZYNIA',
  'CONE': 'PACHOŁEK',
  'BARRIER': 'BARIERKA',
  'TYRES': 'OPONY',
  'FRUIT STAND': 'STRAGAN Z OWOCAMI',
  'FLAMINGO': 'FLAMING',
  'GNOME': 'KRASNAL',
  'FENCE': 'PŁOT',
  'LETTERBOX': 'SKRZYNKA NA LISTY',
  'DECKCHAIR': 'LEŻAK',
  'PARASOL': 'PARASOL',
  'FISH STALL': 'STRAGAN Z RYBAMI',
  'LOBSTER POT': 'KOSZ NA HOMARY',

  // the kit (sim/garage/kit.ts)
  'TRAFFIC CONE': 'PACHOŁEK DROGOWY',
  'RUBBER DUCK': 'GUMOWA KACZKA',
  'SHARK FIN': 'PŁETWA REKINA',
  'CROWN': 'KORONA',
  'TRAFFIC LIGHT': 'SYGNALIZATOR',
  'GIANT DONUT': 'WIELKI DONUT',
  'SATELLITE DISH': 'ANTENA SATELITARNA',
  'MATTRESS': 'MATERAC',
  'TROPHY': 'PUCHAR',
  'FLOWER POTS': 'DONICZKI',
  'PIZZA SLICE': 'KAWAŁEK PIZZY',
  'AMBER BEACON': 'POMARAŃCZOWY KOGUT',
  'DISCO LIGHT BAR': 'DYSKO-KOGUT',
  'FLAGS': 'FLAGI',
  'PROPELLER CAP': 'CZAPKA ZE ŚMIGŁEM',
  'GOLD STAR': 'ZŁOTA GWIAZDA',
  'CYAN NEON': 'BŁĘKITNY NEON',
  'LIME NEON': 'LIMONKOWY NEON',
  'RED NEON': 'CZERWONY NEON',
  'GOLD NEON': 'ZŁOTY NEON',
  'WHITE NEON': 'BIAŁY NEON',
  'VIOLET NEON': 'FIOLETOWY NEON',
  'TWO-TONE NEON': 'DWUKOLOROWY NEON',
  'PINK NEON': 'RÓŻOWY NEON',
  'CLOWN HORN': 'TRĄBKA KLAUNA',
  'GOOSE': 'GĘŚ',
  'DOORBELL': 'DZWONEK',
  'TWO-TONE': 'SYGNAŁ DWUTONOWY',
  'KAZOO': 'KAZOO',
  'AIR HORN': 'TRĄBA PNEUMATYCZNA',
  'BLUE FLAME': 'NIEBIESKI PŁOMIEŃ',
  'GREEN FLAME': 'ZIELONY PŁOMIEŃ',
  'PINK FLAME': 'RÓŻOWY PŁOMIEŃ',
  'WHITE FLAME': 'BIAŁY PŁOMIEŃ',
  'GOLD FLAME': 'ZŁOTY PŁOMIEŃ',
  'RED SMOKE': 'CZERWONY DYM',
  'BLUE SMOKE': 'NIEBIESKI DYM',
  'GREEN SMOKE': 'ZIELONY DYM',
  'PINK SMOKE': 'RÓŻOWY DYM',
  'GOLD SMOKE': 'ZŁOTY DYM',
  'GHOST SMOKE': 'DYM DUCHA',
  'CHROME STARS': 'CHROMOWE GWIAZDY',
  'DEEP DISH': 'GŁĘBOKIE FELGI',
  'GOLD WIRES': 'ZŁOTE SZPRYCHY',
  'WHITE DISCS': 'BIAŁE DEKLE',
  'LIP SPOILER': 'MAŁY SPOJLER',
  'WING': 'SKRZYDŁO',
  'GIANT WING': 'OGROMNE SKRZYDŁO',
  'SLAMMED': 'OBNIŻONE',
  'LIFTED': 'PODNIESIONE',

  // the first quarter hour's steps (sim/run/goal.ts) and the day's challenges (sim/dailies/Dailies.ts)
  'BANK THE BAG': 'WPŁAĆ ŁUP',
  'BUY YOUR FIRST CAR': 'KUP PIERWSZE AUTO',
  'LOSE THE COPS AT ★★': 'ZGUB GLINY PRZY ★★',
  'STEAL A CAR TO ORDER': 'UKRADNIJ AUTO NA ZAMÓWIENIE',
  'BANK 20,000 IN ONE RUN': 'WPŁAĆ 20\u00a0000 W JEDNYM WYPADZIE',
  'BANK 10,000 IN ONE RUN': 'WPŁAĆ 10\u00a0000 W JEDNYM WYPADZIE',
  'BANK 25,000 IN ONE RUN': 'WPŁAĆ 25\u00a0000 W JEDNYM WYPADZIE',
  'BANK 50,000 IN ONE RUN': 'WPŁAĆ 50\u00a0000 W JEDNYM WYPADZIE',
  'ESCAPE FROM ★★★': 'UCIEKNIJ PRZY ★★★',
  'ESCAPE FROM ★★★★★': 'UCIEKNIJ PRZY ★★★★★',
  '3 TAKEDOWNS IN A COMPACT': '3 ELIMINACJE KOMPAKTEM',
  'SMASH 3 BILLBOARDS': 'ROZWAL 3 BILLBOARDY',
  'DELIVER AN ORDER WITHOUT A SCRATCH': 'DOSTARCZ ZAMÓWIENIE BEZ RYSY',
  'COMPLETE 2 DELIVERIES': 'ZALICZ 2 DOSTAWY',
  '2 POLICE TAKEDOWNS': '2 ELIMINACJE RADIOWOZÓW',
  'PICK UP 150 COINS': 'ZBIERZ 150 MONET',
  '10 NEAR MISSES': '10 MIJANEK O WŁOS',
  'BANK 3 RUNS WITHOUT GETTING BUSTED': 'WPŁAĆ ŁUP Z 3 WYPADÓW BEZ WPADKI',
  'SMASH 60 THINGS IN ONE RUN': 'ROZWAL 60 RZECZY W JEDNYM WYPADZIE',
  'FLATTEN 10 LAMP POSTS': 'SKOŚ 10 LATARNI',
};

/** A car's grammatical gender, by its English name: the paint before it agrees (CZERWONY SEDAN, CZERWONA TAKSÓWKA). */
export const PL_GENDER: Readonly<Record<string, 'm' | 'f' | 'n'>> = {
  'MUSCLE CAR': 'm', 'COMPACT': 'm', 'VAN': 'm', 'SPORTS CAR': 'n', 'POLICE CAR': 'm', 'SEDAN': 'm', 'HATCHBACK': 'm',
  'ESTATE': 'n', 'SUV': 'm', 'PICKUP': 'm', 'TAXI': 'f', 'BOX TRUCK': 'm', 'BUS': 'm', 'ICE-CREAM TRUCK': 'm', 'WAGON': 'm',
  'PIZZA HATCH': 'm', 'WRECKER': 'f', 'TWIN': 'm', 'FAKE CRUISER': 'm', 'PARTY BUS': 'm', 'LOWRIDER': 'm', 'GOLD LIMO': 'f',
  'BUBBLE': 'm', 'PHANTOM': 'm', "CHIEF'S CRUISER": 'm', 'ROADSTER': 'm', 'STREET SWEEPER': 'f', 'HOT-DOG VAN': 'm',
};

/** A paint's three forms (masculine, feminine, neuter), by its English name (`PAINT_NAMES`, and ODD for any other). */
export const PL_PAINT: Readonly<Record<string, readonly [string, string, string]>> = {
  'LIME': ['LIMONKOWY', 'LIMONKOWA', 'LIMONKOWE'],
  'CYAN': ['BŁĘKITNY', 'BŁĘKITNA', 'BŁĘKITNE'],
  'ORANGE': ['POMARAŃCZOWY', 'POMARAŃCZOWA', 'POMARAŃCZOWE'],
  'MAGENTA': ['RÓŻOWY', 'RÓŻOWA', 'RÓŻOWE'],
  'WHITE': ['BIAŁY', 'BIAŁA', 'BIAŁE'],
  'BLACK': ['CZARNY', 'CZARNA', 'CZARNE'],
  'MINT': ['MIĘTOWY', 'MIĘTOWA', 'MIĘTOWE'],
  'PEACH': ['BRZOSKWINIOWY', 'BRZOSKWINIOWA', 'BRZOSKWINIOWE'],
  'RED': ['CZERWONY', 'CZERWONA', 'CZERWONE'],
  'YELLOW': ['ŻÓŁTY', 'ŻÓŁTA', 'ŻÓŁTE'],
  'ODD': ['NIETYPOWY', 'NIETYPOWA', 'NIETYPOWE'],
};
